### ISSUE TITLE
Show "early search results" during user input

### ISSUE THREAD

**Issue by mariobehling** [fossasia/loklak_search#100]
Early versions of the search already generated views based on the beginning of the search, similar to Google. Entering search terms now does not generate any "early results".

Please implement searches that start once the user starts typing.

**Comment by hemantjadon** [comment]
@mariobehling This can be closed i guess. Its fixed in PR#126.

* This might seem as not fixed in the first go, but wait for the few seconds for results to be fetched dynamically. (Time delay is purely due to time taken by the server to respond)

* We may add preloader bar (or spinner).

* This will seem more complete once autocomplete is implemented.
