### ISSUE TITLE
Switch site to https

### ISSUE THREAD

**Issue by mariobehling** [fossasia/loklak_search#146]
What needs to be done?

**Comment by hemantjadon** [comment]
Hi @mariobehling 
This not the error with the Loklak Search being deployed on `gh-pages`. I will try to explain what is happening.

* The backend api is deployed on `http`.

* The browsers have a security feature that if the host is `https` they block all the responses to the requests made to unsecure `http` and throw `MixedContent` error.

* We faced this issue also when we first deployed on `gh-pages` with `https` then we made a switch to go with `http://loklak.fossasia.org/` over `http`.

* Now when other developers try to deploy with `gh-pages` for the first time they face this error. This is due to by default `gh-pages` run on `https` and this can't be disabled until custom domain is used (what we did). For more info please check this [HTTPS on gh-pages](https://help.github.com/articles/securing-your-github-pages-site-with-https/).

* So to make the shift Loklak Search to `gh-pages` the first thing will be required is moving the `api endpoint` to `https` then we can simply make the transition.

* Until the backend is migrated to `https` there is nothing much we can do.

I totally understand that this creates the issues for the new developers to start with, but there is not much we can do here until the backend is migrated.

What I can do is explain the situation in README and try to list out the steps developers can take to successfully run a site on `gh-pages` (ie. enabling temporarily the unsafe scripts).

**Comment by Abhi2424shek** [comment]
@mariobehling what @hemantjadon has posted is absolutely correct, we should migrate the backend to https protocol to migrate this project to https protocol.

In my opinion we would need to migrate as Internet security is looming large and more and more security restrictions will occur to the http protocol in the near future
