### ISSUE TITLE
Search results displaying slow

### ISSUE THREAD

**Issue by mariobehling** [fossasia/loklak_search#209]
Even though loklak.org gives out results in a good timeframe results on loklak.net display slowly. Please improve the speed of the site.

**Comment by Achint08** [comment]
Hello @mariobehling Nothing can be done from our side. Data is processed and displayed in microseconds. Problem of time lag is because server takes time to load the result. Only thing  to improve speed  is making fetching faster( done by the server) or request query which is more common.That is not in our hands. Only solution is to reduce search results.

**Comment by mariobehling** [comment]
@Achint08 I see, that loklak.org offers 20 search results as a standard and it relatively fast. loklak.net get 30 results apparently with two requests. The loklak server has implemented pagination, that we can make use of to get faster results potentially as well, e.g. through a "Search More" button. Telling me "it is on the loklak.org site" is not the solution. Please help to find ways to speed it up. Thank you.

**Comment by mariobehling** [comment]
Check out the search here for example:
first page:
http://loklak.org/api/search.json?timezoneOffset=-60&q=singapore&startRecord=1&maximumRecords=10
second page:
http://loklak.org/api/search.json?timezoneOffset=-60&q=singapore&startRecord=10&maximumRecords=10

Works pretty fast for me here right now.

**Comment by Achint08** [comment]
Sorry @mariobehling Indeed it's fast. I meant The data that is fetched. e.g. the profile images takes time for the website. And I didn't knew about pagination thing. :)

**Comment by mariobehling** [comment]
@Achint08 Let's follow up here as well: https://github.com/fossasia/loklak_search/issues/212

**Comment by Achint08** [comment]
Hello @mariobehling @hemantjadon 
This question created a curiosity in me about how google images works so fast since the problem with our website working slow is that we are retrieving so many images at once and that too of large size.
So what can we do is that we can load images depending on the scroll position of our page...
I mean
Suppose you searched for some image, the google will instead prefer to retrieve four/five images only at start but as the user scrolls down it will load images at that instant only.
Check out once. :)
Any more idea? :D

**Comment by Achint08** [comment]
One more thing I came to know that is info-box is making our website slow because
The request for images in info box are like https://avatars.io/twitter/TitouTitoufoot. These are giving bigger images 
![screen shot 2017-01-25 at 12 50 53 am](https://cloud.githubusercontent.com/assets/15813932/22262859/814af170-e298-11e6-81f7-88ad0b40d937.png)

And in feed-cards we are using https://pbs.twimg.com/profile_images/670342479317753857/6ZepUy76_bigger.jpg

![screen shot 2017-01-25 at 12 51 02 am](https://cloud.githubusercontent.com/assets/15813932/22262897/a4b2c17e-e298-11e6-8392-3164f15cda6f.png)

We should retrieve image from this only. :)

**Comment by mariobehling** [comment]
@Achint08 Excellent ideas! Best is to open dedicated issues in future as well. I did that already and assigned you. Would be great if you could help to solve this. Cheers!

**Comment by hemantjadon** [comment]
Search results are now being displayed quite responsively, for frequent queries (which are in ES cache). Also lazy loading of images has been implemented in the application. Closing this for now.
