### ISSUE TITLE
Enabling pc view on phone

### ISSUE THREAD

**Issue by meets2tarun** [fossasia/loklak_search#251]
The task is to create a link down there on the page loklak.net as 
View loklak in Mobile | Deskop 
and whichever is active will have bold black colour and the other one will acts as a link in blue colour.

**Comment by Achint08** [comment]
@meets2tarun  Desktop version on mobile will be useful only if some of the features are not available in mobile version. We can focus instead on mobile version and make all features available on it. 
@mariobehling @hemantjadon  Any suggestion?

**Comment by meets2tarun** [comment]
@Achint08 Those phones so called phablet, need a Desktop view and normal 4.7-5.2 inch phones while using in landscape mode, then a Desktop view matters.
And no doubt, we can even go for making features available for mobile version too.

**Comment by Achint08** [comment]
@meets2tarun in that case , go ahead (Y)

**Comment by hemantjadon** [comment]
@Achint08 @meets2tarun I don't think the special button is required in our use case, as our application as of now is not that complex, and all our features are visible to all our users. And what we should focus on is making site more mobile responsive. Rather than having such button. 

Moreover mobile browsers (I know Chrome for Android) enable us already to switch to the desktop version by itself. (Invalidating `<meta name="viewport" content="width=device-width, initial-scale=1">` ). So in my opinion there is no need of such a button until there is a server which is giving different data (HTML and CSS)  for mobile and desktop (like sites like google and github do) since we are not going to have a server side rendered application in near future (we are serving via gh-pages) we do not need such an option right now.

Your views @mariobehling

**Comment by meets2tarun** [comment]
@hemantjadon Sir,  I totally agree with your opinion but what my point of view is: yeah, we don't require this feature right now but we too don't have any harm getting it and surely tomorrow this feature can help us.

**Comment by yukiisbored** [comment]
There's no need to do this. Because currently this project is responsive as in "one web page for all screens". If you want to view it as if you're on your PC, just use "Request Desktop site" feature from your web browser to lie it's resolution.

**Comment by hemantjadon** [comment]
Closing this for now. If needed please reopen.
