### ISSUE TITLE
A number of searches do not display search results even though server provides results

### ISSUE THREAD

**Issue by mariobehling** [fossasia/loklak_search#267]
I checked the result of from:MartinSchulz. If the user clicks on an @someaccount link on the search results, he/she will quickly discover a number of results that do not show up. Tests on http://api.loklak.org show results though.

![screenshot from 2017-02-09 23-22-15](https://cloud.githubusercontent.com/assets/1583873/22805681/fc2515b4-ef1e-11e6-854b-fb5840adf321.png)

**Comment by uttu357** [comment]
The bug is this : 
   `from:realDonaldTrump` does not return any results, but `from:realdonaldtrump` returns the tweets.

![screenshot from 2017-02-10 13 34 53](https://cloud.githubusercontent.com/assets/15570642/22818977/ee87d0dc-ef95-11e6-920b-c4db82997509.png)
![screenshot from 2017-02-10 13 34 43](https://cloud.githubusercontent.com/assets/15570642/22818980/f1921abc-ef95-11e6-9c01-ac448eb37237.png)

Similarly `from:martinschulz` returns the result but `from:MartinSchulz` do not.

We need to convert all from queries to lowercase before sending the request. Your suggestions? @mariobehling

**Comment by Achint08** [comment]
@uttu357 If you change the source from cache to twitter/all in the request api, even `from:MartinSchulz` will return the result.
We should look forward to source parameter of the api to solve the issue 

When source is set to cache

![screen shot 2017-02-10 at 2 03 58 pm](https://cloud.githubusercontent.com/assets/15813932/22819820/e739f298-ef99-11e6-8617-e5e77bcc19c1.png)

When source is set to all/twitter

![screen shot 2017-02-10 at 2 03 51 pm](https://cloud.githubusercontent.com/assets/15813932/22819835/f577062a-ef99-11e6-8971-45f314cac658.png)

**Comment by hemantjadon** [comment]
I changed it to `all` at some point previously, but it was changed again to `cache` change it back to `all` and the issue will be fixed. 👍 
@Achint08 @uttu357
