### ISSUE TITLE
Queries getting

### ISSUE THREAD

**Issue by mariobehling** [fossasia/loklak_search#287]
For my first query I get "No results found" quite often. The second query then gives me the results.

Please ensure the first query is not failing.

![screenshot from 2017-03-14 12-58-12](https://cloud.githubusercontent.com/assets/1583873/23886459/08b97e4a-08b6-11e7-846b-4a9ea9a6b7e9.png)

**Comment by uttu357** [comment]
The queries are failing because we are sending multiple requests to fetch data separately for the widgets and the main tweets.. This results in `503: Request frequency is too high`. 
Solving this would require either delaying the second request by some time or sending only one request to fetch the data which was the case previously!
Using only one request has further issues as was pointed out by #267 #269 #270.
I think we can delay the second request by a second or two and cancel the previous requests sent during typing the query! This would probably solve the problem but I think there can be a better solution. I would try finding one! Your thoughts @hemantjadon @Achint08 ? :)

**Comment by hemantjadon** [comment]
Request once sent cannot be cancelled (HTTP request) these are not handled, `switchMap` operator. delaying the second request maybe an option, we need to think about it a simple `delay` operator maybe used. But by how much needs to be thought of, as there will be partially unstyled content.

**Comment by mariobehling** [comment]
Delaying is a bad idea. We need to set up a way using keys. So, we allow unlimited access for verified services to the loklak API. All others get limited access. Otherwise they crash our service.

**Comment by hemantjadon** [comment]
@mariobehling Which type of keys are you talking about??

**Comment by Achint08** [comment]
@mariobehling @hemantjadon @uttu357 Sorry. I was involved for my mid sem examinations and then for the visa application. #293 will solve the issue now. Problem initially was that we were sending two request at a time moreover aggregations are I/O expensive so to avoid trafficking we recieved Error 503.  After solving #293, this issue might be solved.
