### ISSUE TITLE
Start Page: Show top hashtags from last 24 hours

### ISSUE THREAD

**Issue by mariobehling** [fossasia/loklak_search#313]
Instead of "Distributed Social Media Message Search Engine" display an area with the top hashtags of the last 24 hours (in simple text style).

Show 12 hashtags here as a link.

![screenshot from 2017-03-30 15-05-35](https://cloud.githubusercontent.com/assets/1583873/24519205/cd908d02-155a-11e7-83b9-29892e4f0e37.png)

**Comment by uttu357** [comment]
Getting hashtags trending globally can result in a single language dominating the trending section as shown for last 24 hours. For example : 
http://loklak.org/api/search.json?q=since:day&timezoneOffset=-330&source=cache&count=0&fields=hashtags

![screenshot from 2017-03-31 03 07 08](https://cloud.githubusercontent.com/assets/15570642/24527305/284a80fe-15bf-11e7-9c1a-5b74e378600a.png)
One thing we can do is get location of the user and use that to get trending relevant to his area as twitter does. We can get the country and city of the user by querying https://www.geoip-db.com/. This would not require any permissions from the user. But we have to rely on third party site for information. Or we can use the geolocation API offered by browsers to get location but it will require the permission for client for using the location. Your suggestions @mariobehling?

**Comment by mariobehling** [comment]
> We can get the country and city of the user

Let's do one thing at a time. Right now the services of loklak often are not reliable and we should do one thing at time and iterate from there.

**Comment by mariobehling** [comment]
Please help to stay focused and introduce one change at a time. We already had issues with the front page not loading at all for many days. Also right now the start page is very slow. So, please do only one change at a time and help to test this carefully at a time. loklak is pretty cool, but does not have many users. In my view the reason is, that it is not reliable - loklak search and loklak server both have issues regularly. Please help to get to everyone to follow best practices that ensure these things do not happen anymore. We need to be more reliable and as you are a core-member of this project now, please help and take responsibility. Test things carefully and look at all details, please. Thank you.

**Comment by uttu357** [comment]
Sure Ill try my best so that it would not be happening any more.
