### ISSUE TITLE
Hide InfoBox and the InfoBox columns when there are no results.

### ISSUE THREAD

**Issue by rishiraj824** [fossasia/loklak_search#322]
- There are various queries for which all the columns inside the InfoBox are empty and it shows a blank box. One should hide it in this case.

![screenshot 90](https://cloud.githubusercontent.com/assets/11540785/24651786/b2f77276-194c-11e7-8115-a0d093f34353.png)

- Also in some case one of the Top Twiterrers, Top Mentions, Top Hashtags are not there in the list but the Heading is displayed. For ex., in this case *Top Mentions*.
![screenshot 91](https://cloud.githubusercontent.com/assets/11540785/24651785/b2f26326-194c-11e7-8fce-eb86f9647087.png)

**Comment by hemantjadon** [comment]
Yeah this will be very nice :)

**Comment by Achint08** [comment]
Hey. This is because of error `Error: statistics is undefined`.  So this error is occurring in info-box component because parameters of the functions (which are processing the aggregations) are undefined. Correct Use of if statement and make those functions run only whenever aggregations are not undefined.

**Comment by rishiraj824** [comment]
@Achint08 Thanks, I'll work on this.
