### ISSUE TITLE
Test app and identify issues

### ISSUE THREAD

**Issue by mariobehling** [fossasia/loklak_search#335]
Test app and perform 10 searches. Note down what happens and which issues appear, e.g. missing sidebars, long loading times, “show more” not working
* Open issues and investigate causes. Propose solutions.
* If issues are relevant for loklak server open issue there and solve it

**Comment by Achint08** [comment]
Hello @mariobehling . I tested the app and these are the problems encountered as per my testing
1. Problem with retrieving aggregations from the server. For some queries, we are not receiving any aggregations. (Server side issue)
2. Retrieving Aggregation data is slower. ( This issue can be avoided since processing aggregation data takes time).
3. On client side , search service in not yet configurable. Aggregation data is common for media search, pagination but multiple requests is being sent to receive aggregations. Instead, only one request should be sent. For `from:user` pattern to search for particular user, aggregations requests should not be sent since it is not displayed.
4. Pagination is not working properly.
5. Problem with receiving results with media.
-  Firstly, unwanted image links are received.
- Pattern for media queries is not giving results with media.
6. For user API requests, sometimes followers topology is not retrieved sometimes. This is the reason followers page is not showing data.

**Comment by mariobehling** [comment]
@Achint08 Thanks. Please open an issue for each problem. We need to work together with the loklak team to solve server issues as well.

**Comment by mariobehling** [comment]
@SarishiNoHara @djmgit @kavithaenair @vibhcool @hemantjadon @singhpratyush @SKrPl

What is your experience with http://loklak.net?
