### ISSUE TITLE
Match design of Media Wall button with Google Search

### ISSUE THREAD

**Issue by mariobehling** [fossasia/loklak_search#450]
![screenshot from 2017-07-12 11-52-49](https://user-images.githubusercontent.com/1583873/28112280-b6684d64-66f8-11e7-8de5-277bf8e006e5.png)

Please improve the following:
* Match speed of dropdown
* Match size of font
* Match distance of box corner to text

**Comment by hemantjadon** [comment]
@mariobehling Would it be nice to have a button instead of a dropdown? #438 
I am saying this as right now to reach the media walls user has to click twice which IMO doesn't seem intuitive.
What I am referring to here is something like this A button to change the UI from feed like to grid?

![screen shot 2017-07-12 at 3 42 16 pm](https://user-images.githubusercontent.com/11755543/28113042-b997b6e4-6718-11e7-8549-bbba7edaeeaf.png)

**Comment by mariobehling** [comment]
@hemantjadon We can follow this "menu" approach as well, but it is not relevant for this feature.

**Comment by apargarg** [comment]
Does it need to be similar to google's settings drop down option?

**Comment by ParthS007** [comment]
@mariobehling Please close this in reference to #607
