### ISSUE TITLE
Add a menu icon and menu items on top right to other FOSSASIA services

### ISSUE THREAD

**Issue by mariobehling** [fossasia/loklak_search#530]
On Google there is a menu icon with different services. Please implement the same in loklak search.

![screenshot from 2017-08-12 01-36-54](https://user-images.githubusercontent.com/1583873/29235427-f2e25122-7efe-11e7-8517-73d1566d58fd.png)

**Comment by hemantjadon** [comment]
@mariobehling What all services are required here in the box?

**Comment by ajayns** [comment]
I'd like to work on this!

**Comment by GingerDragon7** [comment]
is anyone working on this?

**Comment by ParthS007** [comment]
Is this issue still exists? I want to work on this

**Comment by Achint08** [comment]
@GingerDragon7 Please continue with it.

**Comment by ajayns** [comment]
@GingerDragon7 @ParthS007 @Achint08 I had already started working on this then and had to halt work for Loklak started to crash with the update of Angular Material. So since I've already started work, I'll be proceeding with resolving this issue.

**Comment by ParthS007** [comment]
@ajayns There are many issues which are not claimed still, you can work on them as I have mostly done the work related to this PR. You have claimed this issue long time back, I am working on this but then I faced Issue in the local installation that's why I worked on that Issue first because the code of this issue should be tested locally. Please understand. Thanks .

**Comment by ajayns** [comment]
@ParthS007 Alright! Carry on with it then!
