### ISSUE TITLE
Adding of speech to text feature in Loklak_search

### ISSUE THREAD

**Issue by ParthS007** [fossasia/loklak_search#583]
There should be a speech to text feature.
Suggestions required  @hemantjadon  @Achint08 @mariobehling

**Comment by harshit98** [comment]
@ParthS007 Good idea! How you're going to work on it ?

**Comment by 0x48piraj** [comment]
**I'm interested too ! :smile_cat:**

**Comment by ParthS007** [comment]
I am working  on it @0x48piraj

**Comment by 0x48piraj** [comment]
_Ohay!_ :smile:

**Comment by hardy1334** [comment]
I am intrested on working over this,
we can do by using "Annyang JS"

**Comment by simsausaurabh** [comment]
@ParthS007 any updates ?
If you are not currently working on it, I would really like to solve it. I am really interested. :smile:

**Comment by ParthS007** [comment]
ok @simsausaurabh  , Please go ahead 👍

**Comment by simsausaurabh** [comment]
Thanks @ParthS007 I'm on it. :smile:

**Comment by hardy1334** [comment]
I'm working over it

On 24-Jan-2018 2:27 AM, "Saurabh Srivastava" <notifications@github.com>
wrote:

Thanks @ParthS007 <https://github.com/parths007> I'm on it. 😄

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/fossasia/loklak_search/issues/583#issuecomment-359927755>,
or mute the thread

**Comment by simsausaurabh** [comment]
Sorry, but you can't I am already on completion and before that please follow: https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia/ please claim first if you want to work on any issue, and please don't work on the issue which is already taken.

**Comment by hardy1334** [comment]
ok,no problem,you go ahead
