### ISSUE TITLE
Images not showing up in private browsing mode

### ISSUE THREAD

**Issue by mariobehling** [fossasia/loklak_search#59]
With Chrome and Firefox images do not show up in private/incognito browsing mode. I am not clear if this is a Github/Cloudflare issue or caused by us. Other fossasia sites are fine in private mode.

![screenshot from 2016-10-18 00 09 52](https://cloud.githubusercontent.com/assets/1583873/19457685/baecedc6-94c7-11e6-8fbf-adaf65d7477f.png)

**Comment by RyanFitzgerald** [comment]
I seem to be getting a 404 status regardless of if I'm in private or regular browsing mode. It looks like there may be an issue with how the image is being served in general. Was it recently moved or anything like that?

**Comment by hemantjadon** [comment]
@mariobehling @RyanFitzgerald 

This is due to the name mismatch which was changed in #51. So a simple rename in `src/app/feed/feed-header/feed-header.component.ts` will fix this.

Also the issue with the other `profile images` is not in our control. Those are throwing a `404` as their url is malformed in the api or the original user has removed those `images` from their profile.

What we can do is `lazy load` the images using a `web worker` and then if any one of them `404's` we can show a `default image or blur`. 
But this is a progressive enhancement, and what I think is not really required right now, and can be delayed.

Thanks :)

**Comment by sandmanx** [comment]
@mariobehling I am not able to reproduce the bug.
![rsz_screenshot_from_2016-10-27_23-35-56](https://cloud.githubusercontent.com/assets/14184381/19779406/9aa423ac-9c9e-11e6-8f42-77190db029f8.png)

I think it was some temporary problem, as it is working fine now.

**Comment by jig08** [comment]
@mariobehling works fine here too.

<img width="403" alt="screen shot 2016-10-27 at 11 44 23 pm" src="https://cloud.githubusercontent.com/assets/9291400/19779579/4f5756de-9c9f-11e6-96e9-993de1859238.png">

**Comment by mariobehling** [comment]
Ok, thanks. Seems to work now.
