### ISSUE TITLE
News feature take long time to show results.

### ISSUE THREAD

**Issue by praveenojha33** [fossasia/loklak_search#899]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**
The news feature currently keeps on loading for a while for simple query like `fossasia` , `trump` , `india` etc. The results are also relatively less.
**Expected behavior:**
It should load sufficient results quickly.

**Comment by praveenojha33** [comment]
@simsausaurabh Please fix it soon.

**Comment by simsausaurabh** [comment]
@praveenojha33 The api.loklak.org provides results from news organizations and these results are then filtered extensively to match the whole query and show only the results which contain query.

I am getting results, with the current no of news orgs and no of matching results from them provided by api.loklak.org. Please try to mention the issues correctly.The older implementation's filter was not correct due to which we were getting results which totally do not contain the query.

Let's say we get total 20 results and then out of these 20 only 2 are containing the query in it, so we need to show only the relevant 2 not all the 20. The implementation of filter is correct, please see the filter.

We could increase no of news organizations but it has a drawback - ""Making a lot of sequential Http get requests with a large amount of data for each request which are asynchronous causes the subsequent Http requests to fail"". And that is the case with the snapshot you have provided in the issue.

As suggested by @mariobehling, to tackle this problem one way is to show the latest news when there are no results for the query. Currently I have made it to keep searching until we get relevant results. The main idea is to provide the end user relevant results not the irrelevant large no of results.

**Comment by simsausaurabh** [comment]
Making a sequence of http requests for each of the news orgs listed in news config file increase the load time of results. And the no of relevant results in news feed totally depends on the results obtained from api.loklak.org. For making a more stable news feature, it will be great to have a news service/endpoint on loklak_server. A new issue has been created for the same here: [#1620](https://github.com/loklak/loklak_server/issues/1620). Closing this issue here :+1:
